[workspace]
members = ["crates/rustiq-core"]
default-members = [".", "crates/rustiq-core"]
resolver = "2"

[workspace.dependencies]
approx = "0.5.1"
bat = { version = "0.26", default-features = false, features = ["regex-onig"] }
delegate = "0.13"
miette = { version = "7", default-features = false, features = ["derive"] }
nalgebra = { version = "0.35", default-features = false, features = ["std"] }
periodic_table = "0.5"
proptest = "1"
rand = "0.10"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.*"
temp-env = "0.3"
tempfile = "3.27.0"
thiserror = "2"
tokio = { version = "1", default-features = false }
toml-spanner = { version = "1", default-features = false, features = [
  "derive",
  "from-toml",
  "to-toml",
] }

[package]
name = "RustiQ"
description = "The modern rust quantum chemistry software"
authors = ["Mickaël Véril"]
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mveril/RustiQ"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["online"]
online = ["rustiq-core/online", "dep:indicatif", "dep:tokio"]
bench-support = ["rustiq-core/bench-support"]

[dependencies]
rustiq-core = { path = "crates/rustiq-core", version = "0.1.0-alpha.1", default-features = false }
dirs = "7"
miette = { workspace = true, features = ["fancy"] }
toml-spanner.workspace = true
clap = { version = "4.6", features = ["cargo", "derive"] }
indicatif = { version = "0.18", optional = true }
nalgebra.workspace = true
periodic_table.workspace = true
rayon.workspace = true
tokio = { workspace = true, features = ["rt"], optional = true }
serde_json.workspace = true
serde.workspace = true
delegate.workspace = true
thiserror.workspace = true
rand.workspace = true
tabled = "0.22"
humantime = "2"
figlet-rs = "1"
bat = { workspace = true, features = ["paging"] }
cfg-if = "1"
tempfile.workspace = true

[dev-dependencies]
approx.workspace = true
rstest = "0.27"
proptest.workspace = true
temp-env.workspace = true

[[bench]]
name = "eri_timings"
harness = false
required-features = ["bench-support"]

[build-dependencies]
bat = { workspace = true, features = ["build-assets"] }

[profile.profiling]
inherits = "release"
debug = true
