[basis]
name = "cc-pvdz"

[molecule]
geometry = "../anthracene.xyz"
charge = 0
multiplicity = 1
units = "Angstrom"

[method.hf]
max_iterations = 300
convergence_threshold = 1e-8

[method.hf.guess]
type = "CoreHamiltonian"

[method.mp2]
frozen_orbitals = 0

[cache]
enabled = true

[method.hf.diis]
enabled = true
max_history = 6
