[basis]
name = "6-31g"

[molecule]
geometry = "../ethanol.xyz"
charge = 0
multiplicity = 1
units = "Angstrom"

[method.hf]
max_iterations = 100
convergence_threshold = 1e-10

[method.hf.guess]
type = "CoreHamiltonian"

[method.hf.diis]
enabled = true
max_history = 8
