from collections.abc import Iterable
from os import PathLike
from typing import Literal, TypeAlias, overload

__version__: str

Axis: TypeAlias = tuple[float, float, float]
AtomTuple: TypeAlias = tuple[str | int, float, float, float]


class Atom:
    @overload
    def __init__(self, element: str, x: float, y: float, z: float) -> None: ...
    @overload
    def __init__(self, element: int, x: float, y: float, z: float) -> None: ...

    @property
    def element(self) -> str: ...
    @property
    def coordinates(self) -> Axis: ...


AtomLike: TypeAlias = Atom | AtomTuple


class Geometry:
    def __init__(self, atoms: Iterable[AtomLike], comment: str = "") -> None: ...

    @property
    def comment(self) -> str: ...
    @comment.setter
    def comment(self, comment: str) -> None: ...

    def __len__(self) -> int: ...
    def translate(self, translation: Axis) -> None: ...
    def rotate(self, axis: Axis, angle: float) -> None: ...
    def centering(self) -> None: ...
    def mass_centering(self) -> None: ...
    def charge_centering(self) -> None: ...
    def orient_along_principal_axes(self) -> None: ...
    def coordinates(self) -> list[Axis]: ...


class Molecule:
    def __init__(
        self,
        atoms: Iterable[AtomLike],
        charge: int = 0,
        multiplicity: int = 1,
        comment: str = "",
        *,
        units: Literal["bohr", "angstrom"] = "bohr",
    ) -> None: ...

    @property
    def geometry(self) -> Geometry: ...
    @property
    def charge(self) -> int: ...
    @property
    def multiplicity(self) -> int: ...
    @property
    def units(self) -> Literal["bohr", "angstrom"]: ...

class BasisSet:
    @staticmethod
    def from_file(path: str | PathLike[str]) -> BasisSet: ...
    @staticmethod
    def from_json(data: str) -> BasisSet: ...
    @property
    def name(self) -> str: ...

class RHF:
    def __init__(
        self, molecule: Molecule, basis: BasisSet, *,
        max_iterations: int = 100, convergence_threshold: float = 1e-8,
        diis: bool = True, diis_size: int = 6,
    ) -> None: ...
    def run(self) -> HfResult: ...

class UHF:
    def __init__(
        self, molecule: Molecule, basis: BasisSet, *,
        max_iterations: int = 100, convergence_threshold: float = 1e-8,
        diis: bool = True, diis_size: int = 6,
    ) -> None: ...
    def run(self) -> HfResult: ...

class HfResult:
    @property
    def converged(self) -> bool: ...
    @property
    def method(self) -> Literal["RHF", "UHF"]: ...
    @property
    def total_energy(self) -> float: ...
    @property
    def electronic_energy(self) -> float: ...
    @property
    def nuclear_repulsion_energy(self) -> float: ...
    @property
    def iterations(self) -> int: ...
    @property
    def residual_norm(self) -> float: ...
    @property
    def s_squared(self) -> float | None: ...
    @property
    def spin_contamination(self) -> float | None: ...
    def mp2(self, *, frozen_orbitals: int = 0) -> Mp2Result: ...

class Mp2Result:
    @property
    def correlation_energy(self) -> float: ...
    @property
    def electronic_energy(self) -> float: ...
    @property
    def total_energy(self) -> float: ...
    @property
    def frozen_orbitals(self) -> int: ...
